# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitjee', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default='hELLO'),
            preserve_default=False,
        ),
    ]
